### PR TITLE
No burst effects

### PR DESCRIPTION
**Pull request by yousef157**
I fucking committed into the master branch.
Well, here is preview:

https://streamable.com/k72q8

### CODE REVIEW

**Comment by Tanza3D** [comment]
im not sure how this looks, @5pla77er your thoughts?

**Comment by matteofo** [comment]
Numbers too big, also I like the burst effect myself, at least that's what I think, it isn't confusing imo. Also you can do a lot more with separated numbers and hitcircles

**Comment by yousef157** [comment]
> Numbers too big, also I like the burst effect myself, at least that's what I think, it isn't confusing imo. Also you can do a lot more with separated numbers and hitcircles

Streams are easier without the bursts. I like it myself too but it's still distracting.

**Comment by Tanza3D** [comment]
Awaiting smaller numbers on @5pla77er's request.

**Comment by matteofo** [comment]
Smaller numbers would make it much better. So yeah, if you make smaller numbers I guess we could merge.

**Comment by Tanza3D** [comment]
still awaiting smaller numbers

**Pull request merged**
